added keystone-states for Cinder, untested (see below)
I get this error:

----------
          ID: cinder-user in Keystone
    Function: keystone.user_present
        Name: cinder
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1539, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/keystone.py", line 180, in user_present
                  for role in roles[tenant_role]:
              TypeError: list indices must be integers, not OrderedDict
     Started: 16:13:10.859331
    Duration: 67.766 ms
     Changes:
----------

Either keystone changed its behaviour again or Salt's move to
make most things OrderedDicts broke the module.